version: '3.8'
services:
  dev-db:
    image: postgres:alpine3.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - freecodecamp
networks:
 freecodecamp: